env:
	export RUN_ADDRESS="127.0.0.1:8080"
	export ACCRUAL_SYSTEM_ADDRESS="127.0.0.1"
	export DATABASE_URI="host=localhost port=5432 user=gofermart password=gofermart dbname=gofermart sslmode=disable connect_timeout=5"
